Time::DATE_FORMATS[:default] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:datetime] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:date] = '%Y/%m/%d'
Time::DATE_FORMATS[:time] = '%H:%M:%S'
Time::DATE_FORMATS[:time_short] = '%H:%M'
Date::DATE_FORMATS[:default] = '%Y/%m/%d'
Date::DATE_FORMATS[:date_short] = '%m/%d'
