# config/app.yml for rails-settings-cached
defaults: &defaults
  trash_rotation:
    0: -1
    1: 0
    2: 1
    3: -1
    4: 0
    5: 2
    6: -1
  exchange_before: 'USD'
  exchange_after: 'JPY'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
