# config/app.yml for rails-settings-cached
defaults: &defaults
  trash_rotation:
    0: 'なし'
    1: '一般ゴミ'
    2: '資源ごみ'
    3: 'なし'
    4: '一般ゴミ'
    5: '容器包装プラゴミ'
    6: 'なし'
  exchange_before: 'USD'
  exchange_after: 'JPY_T'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
